<?php
class TemplateToaster_Theme_Options_Dynamic
{
public $sections;
public $checkboxes;
public $contactvar;
public $settings;

 /*** Construct ***/
public function __construct()
{
// This will keep track of the checkbox options for the validate_settings function.
$this->checkboxes = array();
$this->settings = array();
$this->get_dynamic_options();
$this->sections['header'] = __('Header', 'TT-7theme--0066');
$this->sections['postcontent'] = __('Post/Content', 'TT-7theme--0066');
$this->sections['footer'] = __('Footer', 'TT-7theme--0066');
$this->sections['colors'] = __('Colors', 'TT-7theme--0066');
$this->sections['generaloptions'] = __('General', 'TT-7theme--0066');
$contactvar=get_option('contact_form',"ttr_test");
if( $contactvar == "ttr_test") {
$adminmail=get_option('admin_email');
$default=array(0=>array('ttr_email'=>''),1=>array('ttr_captcha_public_key'=>''),2=>array('ttr_captcha_private_key'=>''),3=>array('ttr_contact_us_error_message'=>'Message was not sent. Try Again.'),4=>array('ttr_contact_us_success_message'=>'Thanks! Your message has been sent.'));
update_option( 'contact_form', $default );
}
}
public function get_dynamic_options()
{
$menulogo = get_template_directory_uri() . '/menulogo.png';
$headerlogo = get_template_directory_uri() . '/logo.png';
$headerrss = get_template_directory_uri().'/images/headerrss.png';
$headerfacebook = get_template_directory_uri().'/images/headerfacebook.png';
$headerlinkedin = get_template_directory_uri().'/images/headerlinkedin.png';
$headertwitter = get_template_directory_uri().'/images/headertwitter.png';
$headergoogleplus = get_template_directory_uri() . '/images/headergoogleplus.png';
$footerrss = get_template_directory_uri().'/images/footerrss.png';
$footertwitter = get_template_directory_uri().'/images/footertwitter.png';
$footergoogleplus = get_template_directory_uri() . '/images/footergoogleplus.png';
$footerfacebook = get_template_directory_uri().'/images/footerfacebook.png';
$footerlinkedin = get_template_directory_uri().'/images/footerlinkedin.png';
$favicon = get_template_directory_uri().'/favicon.ico';
$copyright_url = home_url();
$facebook_url = 'http://www.facebook.com/TemplateToaster';
$linkedin_url = 'http://www.templatetoaster.com';
$twitter_url = 'http://twitter.com/templatetoaster';
$googleplus_url = 'http://www.templatetoaster.com';
$footer_facebook_url = 'http://www.facebook.com/TemplateToaster';
$footer_linkedin_url = 'http://www.templatetoaster.com';
$footer_twitter_url = 'http://twitter.com/templatetoaster';
$footer_googleplus_url = 'http://www.templatetoaster.com';
/* Color Settings */

$this->settings['ttr_title'] = array(
'title' => __('Site Title Color', 'TT-7theme--0066'),
'desc' => __('Choose site title color', 'TT-7theme--0066'),
'std' => '',
/*'class' => 'colorwell',*/
'type' => 'colorpicker',
'section' => 'colors');
$this->settings['ttr_slogan'] = array(
'title' => __('Site Slogan Color', 'TT-7theme--0066'),
'desc' => __('Choose site slogan color', 'TT-7theme--0066'),
'std' => '',
/*'class' => 'colorwell',*/
'type' => 'colorpicker',
'section' => 'colors');
$this->settings['ttr_copyright'] = array(
'title' => __('Footer Copyright Color', 'TT-7theme--0066'),
'desc' => __('Choose footer copyrightcolor', 'TT-7theme--0066'),
'std' => '',
/*'class' => 'colorwell',*/
'type' => 'colorpicker',
'section' => 'colors');
$this->settings['ttr_blockheading'] = array(
'title' => __('Block Heading Color', 'TT-7theme--0066'),
'desc' => __('Choose block heading color', 'TT-7theme--0066'),
'std' => '',
/*'class' => 'colorwell',*/
'type' => 'colorpicker',
'section' => 'colors');
$this->settings['ttr_post_title_color'] = array(
'title' => __('Page/Post Title Normal Color', 'TT-7theme--0066'),
'desc' => __('Choose Page/Post title normal color', 'TT-7theme--0066'),
'std' => '',
/*'class' => 'colorwell',*/
'type' => 'colorpicker',
'section' => 'colors');
$this->settings['ttr_post_title_hover_color'] = array(
'title' => __('Post Title Hover Color', 'TT-7theme--0066'),
'desc' => __('Choose post title hover color', 'TT-7theme--0066'),
'std' => '',
/*'class' => 'colorwell',*/
'type' => 'colorpicker',
'section' => 'colors');
/* Post/Content Settings */
$this->settings['ttr_featured_post'] = array(
'title' => __('Number of Featured Posts', 'TT-7theme--0066'),
'desc' => __('How many posts would you like to be displayed as featured on the front page?', 'TT-7theme--0066'),
'std' => '1',
'pattern' => '\d+',
'type' => 'text',
'section' => 'postcontent');
$this->settings['ttr_post_layout'] = array(
'title' => __('Number of Columns', 'TT-7theme--0066'),
'desc' => __('How many columns would you like to display the posts after featured posts', 'TT-7theme--0066'),
'std' => '4',
'pattern' => '\d+',
'type' => 'text',
'section' => 'postcontent');
$this->settings['ttr_page_breadcrumb'] = array(
'title' => __('Show Breadcrumbs On Page', 'TT-7theme--0066'),
'desc' => __('Check this box if you would like to ENABLE the Breadcrumbs On Page', 'TT-7theme--0066'),
'std' => 0,
'type' => 'checkbox',
'section' => 'postcontent');
$this->settings['ttr_post_breadcrumb'] = array(
'title' => __('Show Breadcrumbs On Post', 'TT-7theme--0066'),
'desc' => __('Check this box if you would like to ENABLE the Breadcrumbs On Post', 'TT-7theme--0066'),
'std' => 0,
'type' => 'checkbox',
'section' => 'postcontent');
$this->settings['ttr_breadcrumb_text'] = array(
'title' => __('Breadcrumbs Prefix', 'TT-7theme--0066'),
'desc' => __('Choose breadcrumbs text', 'TT-7theme--0066'),
'std' => '',
'type' => 'text',
'section' => 'postcontent');
$this->settings['ttr_breadcrumb_text_separator'] = array(
'title' => __('Breadcrumbs Separator', 'TT-7theme--0066'),
'desc' => __('Set your Breadcrumbs separator', 'TT-7theme--0066'),
'std' => '',
'type' => 'text',
'section' => 'postcontent');
 /*** Header ***/
$this->settings['ttr_site_title_slogan_enable'] = array(
'title' => __('Display Website Title And Slogan', 'TT-7theme--0066'),
'desc' => __('Enable/Disable Website Title And Slogan', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'header');
$this->settings['ttr_site_title_enable'] = array(
'title' => __('Display Website Title', 'TT-7theme--0066'),
'desc' => __('Enable/Disable Website Title', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'header');
$this->settings['ttr_font_size_title'] = array(
'title' => __('Website Title Font Size', 'TT-7theme--0066'),
'desc' => __('Enter the font size of Site title here', 'TT-7theme--0066'),
'std' => '',
'pattern' => '\d+',
'type' => 'text',
'section' => 'header');
$this->settings['ttr_heading_tag_title'] = array(
'title' => __('Heading Tag for Website Title', 'TT-7theme--0066'),
'desc' => __('Choose heading tag for Site Title', 'TT-7theme--0066'),
'type' => 'select',
'std' => 'h1',
'choices' => array(
'choice1' => __('h1', 'TT-7theme--0066'),
'choice2' => __('h2', 'TT-7theme--0066'),
'choice3' => __('h3', 'TT-7theme--0066'),
'choice4' => __('h4', 'TT-7theme--0066'),
'choice5' => __('h5', 'TT-7theme--0066'),
'choice6' => __('h6', 'TT-7theme--0066'),
'choice7' => __('p', 'TT-7theme--0066')),
'section' => 'header');
$this->settings['ttr_site_slogan_enable'] = array(
'title' => __('Display Website Slogan', 'TT-7theme--0066'),
'desc' => __('Check this box if you would like to ENABLE the site slogan', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'header');
$this->settings['ttr_font_size_slogan'] = array(
'title' => __('Website Slogan Font Size', 'TT-7theme--0066'),
'desc' => __('Enter the font size of Site Slogan', 'TT-7theme--0066'),
'std' => '',
'pattern' => '\d+',
'type' => 'text',
'section' => 'header');
$this->settings['ttr_heading_tag_slogan'] = array(
'title' => __('Heading Tag for Website Slogan', 'TT-7theme--0066'),
'desc' => __('Enter the font size of Site Slogan', 'TT-7theme--0066'),
'type' => 'select',
'std' => 'p',
'choices' => array(
'choice1' => __('h1', 'TT-7theme--0066'),
'choice2' => __('h2', 'TT-7theme--0066'),
'choice3' => __('h3', 'TT-7theme--0066'),
'choice4' => __('h4', 'TT-7theme--0066'),
'choice5' => __('h5', 'TT-7theme--0066'),
'choice6' => __('h6', 'TT-7theme--0066'),
'choice7' => __('p', 'TT-7theme--0066')),
'section' => 'header');
/* Footer Settings */

$this->settings['ttr_copyright_text'] = array(
'title' => __('Footer Copyright Text', 'TT-7theme--0066'),
'desc' => __('Enter copyright text', 'TT-7theme--0066'),
'std' => 'Copyright © 2019 | Privacy policy',
'type' => 'textarea',
'section' => 'footer');
$this->settings['ttr_copyright_url'] = array(
'title' => __('Footer Copyright URL', 'TT-7theme--0066'),
'desc' => __('Enter copyright url', 'TT-7theme--0066'),
'std' => $copyright_url,
'type' => 'textarea',
'section' => 'footer');
$this->settings['ttr_copyright_disable'] = array(
'title' => __('Display Footer Copyright', 'TT-7theme--0066'),
'desc' => __('ENABLE/DISABLE the footer copyright', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'footer');
$this->settings['ttr_font_size_copyright'] = array(
'title' => __('Footer Copyright Font Size', 'TT-7theme--0066'),
'desc' => __('Enter the font size of Footer Copyright', 'TT-7theme--0066'),
'std' => '',
'type' => 'text',
'section' => 'footer');
$this->settings['ttr_facebook'] = array(
'title' => __('Upload your Facebook Icon', 'TT-7theme--0066'),
'desc' => __('Upload your Facebook Icon', 'TT-7theme--0066'),
'std' => $footerfacebook,
'type' => 'media',
'section' => 'footer');
$this->settings['ttr_facebook_enable'] = array(
'title' => __('Display Facebook Icon', 'TT-7theme--0066'),
'desc' => __('ENABLE/DISABLE the Facebook Icon', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'footer');
$this->settings['ttr_facebook_url'] = array(
'title' => __('Facebook Icon URL', 'TT-7theme--0066'),
'desc' => __('Enter Facebook url', 'TT-7theme--0066'),
'std' => $footer_facebook_url,
'type' => 'textarea',
'section' => 'footer');
$this->settings['ttr_twitter'] = array(
'title' => __('Upload your Twitter Icon', 'TT-7theme--0066'),
'desc' => __('Upload your Twitter Icon', 'TT-7theme--0066'),
'std' => $footertwitter,
'type' => 'media',
'section' => 'footer');
$this->settings['ttr_twitter_enable'] = array(
'title' => __('Display Twitter Icon', 'TT-7theme--0066'),
'desc' => __('ENABLE/DISABLE the Twitter Icon', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'footer');
$this->settings['ttr_twitter_url'] = array(
'title' => __('Twitter Icon URL', 'TT-7theme--0066'),
'desc' => __('Enter Twitter url', 'TT-7theme--0066'),
'std' => $footer_twitter_url,
'type' => 'textarea',
'section' => 'footer');
$this->settings['ttr_googleplus'] = array(
'title' => __('Upload your GooglePlus Icon', 'TT-7theme--0066'),
'desc' => __('Upload your GooglePlus Icon', 'TT-7theme--0066'),
'std' => $footergoogleplus,
'type' => 'media',
'section' => 'footer');
$this->settings['ttr_googleplus_enable'] = array(
'title' => __('Display GooglePlus Icon', 'TT-7theme--0066'),
'desc' => __('ENABLE/DISABLE the GooglePlus Icon', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'footer');
$this->settings['ttr_googleplus_url'] = array(
'title' => __('GooglePlus Icon URL', 'TT-7theme--0066'),
'desc' => __('Enter GooglePlus url', 'TT-7theme--0066'),
'std' => $footer_googleplus_url,
'type' => 'textarea',
'section' => 'footer');
$this->settings['ttr_show_social_media_enable'] = array(
'title' => __('Show Social Media Icons', 'TT-7theme--0066'),
'desc' => __('ENABLE/DISABLE Social Media icons', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'footer');
$this->settings['ttr_link_new_window_enable'] = array(
'title' => __('Open Social Media Links In A New Window', 'TT-7theme--0066'),
'desc' => __('ENABLE/DISABLE to Open Social Media Links In A New Window', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'footer');
$this->settings['ttr_no_follow'] = array(
'title' => __('Enable rel="nofollow"', 'TT-7theme--0066'),
'desc' => __('ENABLE/DISABLE to rel=follow', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'footer');
/** General Options **/

$this->settings['ttr_theme_bootstrap_enable'] = array(
'title' => __('Enable Theme Bootstrap Javascipt', 'TT-7theme--0066'),
'desc' => __('ENABLE/DISABLE Theme Bootstrap Javascipt', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_google_analytics'] = array(
'title' => __('Google Analytics', 'TT-7theme--0066'),
'desc' => __('Text Box for google analytics', 'TT-7theme--0066'),
'std' => '',
'type' => 'textarea',
'section' => 'generaloptions');
$this->settings['ttr_google_analytics_enable'] = array(
'title' => __('Enable Google Analytics', 'TT-7theme--0066'),
'desc' => __('ENABLE/DISABLE Google Analytics', 'TT-7theme--0066'),
'std' => 0,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_custom_style'] = array(
'title' => __('Custom CSS', 'TT-7theme--0066'),
'desc' => __('Text Box for custom css', 'TT-7theme--0066'),
'std' => '',
'type' => 'textarea',
'section' => 'generaloptions');
$this->settings['ttr_all_page_title'] = array(
'title' => __('Display All Page Titles', 'TT-7theme--0066'),
'desc' => __('On/Off the page title', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_all_post_title'] = array(
'title' => __('Display All Post Titles', 'TT-7theme--0066'),
'desc' => __('On/Off the post title', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_remove_date'] = array(
'title' => __('Display Post Date', 'TT-7theme--0066'),
'desc' => __('On/Off the post date', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_remove_author_name'] = array(
'title' => __('Display Author Name', 'TT-7theme--0066'),
'desc' => __('On/Off the author name', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_remove_post_category'] = array(
'title' => __('Show Post Category', 'TT-7theme--0066'),
'desc' => __('Show Post Category', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_post_navigation_above'] = array(
'title' => __('Display Navigation above the posts', 'TT-7theme--0066'),
'desc' => __('Show/Hide navigation above the posts', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_post_navigation_below'] = array(
'title' => __('Display Navigation below the posts', 'TT-7theme--0066'),
'desc' => __('Show/Hide navigation below the posts', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_older_newer_posts_above'] = array(
'title' => __('Display Older/Newer Posts Link  above the posts', 'TT-7theme--0066'),
'desc' => __('Show/Hide Older/Newer Posts Link above the posts', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_older_newer_posts_below'] = array(
'title' => __('Display Older/Newer Posts Link below the posts', 'TT-7theme--0066'),
'desc' => __('Show/Hide Older/Newer Posts Link below the posts', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_post_navigation_post'] = array(
'title' => __('Display Post Navigation', 'TT-7theme--0066'),
'desc' => __('Show/Hide post navigation', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_post_category_post'] = array(
'title' => __('Display Post Category', 'TT-7theme--0066'),
'desc' => __('Show/Hide post Category', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_previous_next_links'] = array(
'title' => __('Display Previous/next Posts Link', 'TT-7theme--0066'),
'desc' => __('Show/Hide Previous/next  Posts Link', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_pagination_link_posts_above'] = array(
'title' => __('Display Pagination Link Of Post Pages above the posts', 'TT-7theme--0066'),
'desc' => __('Show/Hide Pagination Link Of Post Pages above the posts', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_pagination_link_posts_below'] = array(
'title' => __('Display Pagination Link Of Post Pages below the posts', 'TT-7theme--0066'),
'desc' => __('Show/Hide Pagination Link Of Post Pages  below the posts', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_comments_closed_text'] = array(
'title' => __('Display Comments are closed ', 'TT-7theme--0066'),
'desc' => __('Show/Hide Comments are closed', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_comments_list'] = array(
'title' => __('Display Comments List', 'TT-7theme--0066'),
'desc' => __('Show/Hide Comments ', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_comments_form'] = array(
'title' => __('Display Comments Form', 'TT-7theme--0066'),
'desc' => __('Show/Hide Comment form ', 'TT-7theme--0066'),
'std' => 0,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_comment_list_form'] = array(
'title' => __('Show Comments list', 'TT-7theme--0066'),
'desc' => __('Check this box to show comment form below comments list.', 'TT-7theme--0066'),
'type' => 'radio',
'std' => 'choice1',
'choices' => array(
'choice1' => __('Above Comment Form', 'TT-7theme--0066'),
'choice2' => __('Below Comment Form', 'TT-7theme--0066')
),
'section' => 'generaloptions');
$this->settings['ttr_avatar_size'] = array(
'title' => __('Avatar Size', 'TT-7theme--0066'),
'desc' => __('Set Avatar size ', 'TT-7theme--0066'),
'std' => '',
'pattern' => '\d+',
'type' => 'text',
'section' => 'generaloptions');
$this->settings['ttr_back_to_top'] = array(
'title' => __('Display Back To Top Button', 'TT-7theme--0066'),
'desc' => __('on/off the back to top button', 'TT-7theme--0066'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_icon_back_to_top'] = array(
'title' => __('Choose icon for Back To Top Button', 'TT-7theme--0066'),
'desc' => __('Choose icon for back to top button', 'TT-7theme--0066'),
'std' => '',
'type' => 'media',
'section' => 'generaloptions');
$this->settings['ttr_read_more'] = array(
'title' => __('Read More Text', 'TT-7theme--0066'),
'desc' => __('Change Text For Read More Link', 'TT-7theme--0066'),
'std' => __('Continue Reading', 'TT-7theme--0066'),
'type' => 'text',
'section' => 'generaloptions');
$this->settings['ttr_read_more_button'] = array(
'title' => __('Display Button For Read More', 'TT-7theme--0066'),
'desc' => __('Enable/Disable the Read More button', 'TT-7theme--0066'),
'std' => 0,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_post1_enable'] = array(
'title' => __('Read more on all posts', 'TT-7theme--0066'),
'desc' => __('on/off the Read More on all posts', 'TT-7theme--0066'),
'std' => 0,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_read_length'] = array(
'title' => __('Word Count', 'TT-7theme--0066'),
'desc' => __('After how many words you need read more', 'TT-7theme--0066'),
'std' => '',
'pattern' => '\d+',
'type' => 'text',
'section' => 'generaloptions');
$this->settings['ttr_search_icon_enable'] = array(
'title' => __('Display Search Icon In Search Widget', 'TT-7theme--0066'),
'desc' => __('Display/Hide Search Icon', 'TT-7theme--0066'),
'std' => 0,
'type' => 'checkbox',
'section' => 'generaloptions');
}
}
?>
